language: objective-c
osx_image: xcode7
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - sudo motion update
install:
  - bundle
  - pod setup > /dev/null
  - rake pod:install
script: bundle exec rake spec
